In [94]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')

from elasticsearch import Elasticsearch
import pandas as pd
import json
import sqlite3
import pyodbc
from GetWorkFlow.db import DB
from elasticsearch import helpers
import requests

from elastic_settings import (
    all_cols,
    nested_cols,
    query_fields,
    INDEX_NAME,
    mappings,
    make_request_body,
    get_auth_header,
    make_elastic_query
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [95]:
from datetime import datetime, timedelta, timezone
(datetime.now(timezone.utc) - timedelta(minutes=1)).strftime('%Y-%m-%dT%H:%M:%S')

'2022-05-11T18:43:18'

### Credentials

In [96]:
from all_envs import *

In [97]:
spvars = test_SPVars()

SPVars(base_url='https://operationcentre.ms.bell.ca', env='PROD', client_secret='845e3004-c0f2-41c7-845f-2dd89481c842', user='svc-oc-smarttask-a', pw='bwx6BTQ!uqe-dxn2vtk')

In [124]:
def get_service_user_OC_token(sp_vars):
    """Post request to generate authentication token"""

    url = f"{sp_vars.base_url}/auth/realms/oc/protocol/openid-connect/token"

    payload=f"grant_type=password&client_id=oc-backend&"+\
            f"client_secret={sp_vars.client_secret}&"+\
            f"username={sp_vars.user}&password={sp_vars.pw}"
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Cookie': 'db4fdfa0d404bc10acda4670ccb15825=2a50a3c37d5e6020cba6f3bc9a4833a3; e69f1ea65bfd1ce3ad5996309f24ac3e=263f5d6acf2eb274a1d87c25ac4c33ad'
    }

    return requests.request("POST", url, headers=headers, data=payload, verify=False)


def smarttask_api_search_request(sp_vars, auth_header, date, limit=500):
    """Search the API based on payload found in elastic_settings.py
    The date in this payload is dynamic"""

    url = f"{sp_vars.base_url}/api/service-order/smarttask/order/_search?offset=0&limit={limit}&fields="

    payload = json.dumps(make_request_body(date=date))
    headers = get_auth_header(auth_header)

    return requests.request("POST", url, headers=headers, data=payload, verify=False)

In [125]:
def start_scroll_elastic_requests(sp_vars, auth_header, date, limit):

  url = f"{sp_vars.base_url}/api/service-order/smarttask/order/_startScroll?offset=0&limit={limit}&fields="

  payload = json.dumps(make_request_body(date=date))
  headers = get_auth_header(auth_header)

  return requests.request("POST", url, headers=headers, data=payload, verify=False)

In [126]:
def continue_scroll_elastic_requests(sp_vars, auth_header, date, scroll_id):

  url = f"{sp_vars.base_url}/api/service-order/smarttask/order/_continueScroll?scrollId={scroll_id}"

  payload = json.dumps(make_request_body(date=date))
  headers = get_auth_header(auth_header)

  return requests.request("POST", url, headers=headers, data=payload, verify=False)

In [127]:

service_token = get_service_user_OC_token(sp_vars)
access_token = json.loads(service_token.text)['access_token']

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

### Scroll Tests

In [10]:
index_name = 'bbm_aiml_stm_prod_test_2'

from initialize_elastic_index import prepare_data_and_load_to_index
from elastic_api_index import initialize_elastic_connection

es_connection = initialize_elastic_connection()

service_token = get_service_user_OC_token(sp_vars)
access_token = json.loads(service_token.text)['access_token']
start_response = start_scroll_elastic_requests(sp_vars, access_token, "2022-05-08T12:03:41", 500)
scroll_id = start_response.headers['x-scroll-id']

prepare_data_and_load_to_index(es_connection, 
                                json.loads(start_response.text)['results'],
                                index_name)

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\elasticsearch\connection\http_urllib3.py:209: UserWarning: Connecting to https://paas-mtrl-blmcih-data-03.qc.bell.ca:9200 using SSL with verify_certs=False is insecure.
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\elasticsearch\helpers\actions.py:240: ElasticsearchWarning: The client is unable to verify that the server is Elasticsearch due security privileges on the server side
  resp = client.bulk(*args, body="\n".join(bulk_actions) + "\n", **kwargs)
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic

In [11]:
import time
while True:
    start_time = time.time()

    next_scroll_response_raw = continue_scroll_elastic_requests(
            sp_vars, access_token, "2022-05-08T12:03:41", scroll_id
        )
    next_scroll_response_text = json.loads(next_scroll_response_raw.text)

    try:
        next_scroll_results = next_scroll_response_text['results']
    except:
        print(next_scroll_response_text)
        break
    prepare_data_and_load_to_index(es_connection, next_scroll_results, index_name)
    
    print(f"---{time.time() - start_time} seconds ---")

    if not next_scroll_results:
        break

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---12.268925189971924 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---12.434939861297607 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---11.790895700454712 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---11.720884561538696 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---12.34994387626648 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---13.075059413909912 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---13.330009460449219 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---13.469013929367065 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---12.921982765197754 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---13.818039894104004 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---13.188001871109009 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.7237069606781 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---14.266078472137451 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---14.600107192993164 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---21.059521436691284 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.41116452217102 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---14.61510682106018 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---14.505095720291138 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.630507469177246 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.857024908065796 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.61318302154541 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---15.34616208076477 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

Finished indexing data to Elastic
---3.2192413806915283 seconds ---
Empty dict - Nothing was indexed
---0.21305012702941895 seconds ---

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [35]:
l_start = json.loads(r.text)['results']
l_cont = json.loads(c.text)['results']

In [66]:
# Test for duplicate request_ids
from collections import Counter
max(Counter([d['id'] for d in l_start]).values())

2

### Mapping & indexing tests

What we are testing:

1. For each flattened field, we cannot use 'nan' values when there is no data. If there is no data for a flattened field, we must represnt the fact that there is no data by a dictionary. 
2. Some requests have nested data that other requests don't have. Therefore, subfields names can be different from one request to the next. Does this difference get appropriatly indexed in Elastic?
3. When the same flattend field has different nested levels (because of 1 and 2), does this difference get appropriatly indexed in Elastic?

In [128]:
r = smarttask_api_search_request(sp_vars, access_token, "2020-04-27T10:20:55")

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'operationcentre.ms.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [108]:
r.text

'{"metadata":{"offset":0,"limit":500,"totalRecordCount":18302},"results":[{"id":"bsd_REQ-545588","lastUpdated":"2022-05-11T18:45:47.912101108Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545588","status":"new","controlDesk":"managedServicesSPOA","group":"Queue not found","tags":["CREATED_FROM_EMAIL_REQUEST","AIML_PROCESSED","SMARTPATH_DISTRIBUTION_MODE_QUEUE"]},"source":{"id":"bsd_REQ-545588","externalId":"REQ-545588","emailSubject":"SR886118 - Please be advised that a new worklog has been created./ Veuillez remarquer qu\'une entrée du journal des travaux a été créée.","orderDate":"2022-05-11T18:45:43Z","requestedStartDate":"2022-05-11T18:45:43Z","lastUpdated":"2022-05-11T18:45:47.910303932Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"generalInquiry-othergeneral","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Retail","incomingMailbox":"cibcmac@bell.ca","status":"acknowledged","product":"managedServices","serviceRegion":"ON","originator":{"email":"DoNotReply-Mx@bell.ca","name":"DoNotReply-Mx@bell.ca"},"preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"General Inquiry - Other","status":"Acknowledged","product":"Managed Infrastructure Services"}},"fr":{"source":{"requestType":"Demande générale - Autre","status":"Reçue","product":"Services gérés d’infrastructure"}}}},{"id":"bsd_REQ-545587","lastUpdated":"2022-05-11T18:45:35.300776606Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545587","status":"new","controlDesk":"bbscL2","tags":["SMARTPATH_COPY","SMARTPATH_DISTRIBUTION_MODE_FILTER","CREATED_FROM_SMARTPATH","COPIED_FROM_SMARTPATH"]},"source":{"id":"bsd_REQ-545587","externalId":"REQ-545587","orderDate":"2022-05-11T18:45:23Z","requestedStartDate":"2022-05-03T21:33:01Z","lastUpdated":"2022-05-11T18:45:35.298856087Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"billingInquiry-copyofinvoice","requestSource":"smartpath","customerSupportModel":"Standard","businessUnit":"Retail","existingAddress":"","siteA":"","site":{"existing":{"address":""},"installation":{"address":""}},"crdDdst":"NXEDSAU","status":"acknowledged","product":"megaLink","serviceRegion":"WEST","billingAddress":"","goldenCustomer":{"id":"1004693299","name":"CAA"},"customer":{"name":"CAA"},"creator":{"id":"michael.ahmad","email":"michael.ahmad@bell.ca","name":"Michael Ahmad"},"originator":{"email":"anson.au@bell.ca","phoneNumber":"4166054074","name":"ANson Au","type":""},"customerMarketSegment":"Ontario Enterprise","preferredLanguage":"en","relatedOrder":[{"id":"bsd_REQ-532223","sourceSystemId":"BSD","relationType":"origin"}]},"fullTextSearch":{"en":{"source":{"requestType":"Billing Inquiry - Copy of invoice","status":"Acknowledged","product":"Megalink or ISDN PRI"}},"fr":{"source":{"requestType":"Facturation - Copie de facture","status":"Reçue","product":"Megalink ou IDP RNIS"}}}},{"id":"bsd_REQ-545586","lastUpdated":"2022-05-11T18:45:27.959925974Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545586","status":"redistribute","controlDesk":"businessCare","tags":["CREATED_FROM_SMARTPATH","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545586","externalId":"REQ-545586","orderDate":"2022-05-11T18:45:12Z","requestedStartDate":"2022-05-11T18:45:12Z","lastUpdated":"2022-05-11T18:45:27.958458511Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"winback","requestSource":"smartpath","billingAccount":"","customerSupportModel":"Standard","businessUnit":"Retail","crdDdst":"NXS4B83","status":"inProgress","product":"businessLines","serviceRegion":"ON","requestedCompletionDate":"2022-05-13T04:00:00Z","goldenCustomer":{"id":"1004700270","name":"United Parcel Service Canada Ltd."},"customer":{"name":"United Parcel Service Canada Ltd."},"creator":{"id":"de6109904","email":"derrick.fishwick@bell.ca","name":"Derrick Fishwick"},"originator":{"email":"derrick.fishwick@bell.ca","phoneNumber":"437-329-5062","name":"Derrick Fishwick"},"customerMarketSegment":"Ontario Enterprise","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"Winback","status":"In progress","product":"Business Lines"}},"fr":{"source":{"requestType":"Retour à Bell","status":"En cours","product":"Lignes locales ou interurbain"}}}},{"id":"bsd_REQ-545584","lastUpdated":"2022-05-11T18:44:56.637376276Z","accessPolicyTag":["DIVISION_RETAIL","TEST"],"workOrder":{"id":"bsd_REQ-545584","status":"new","controlDesk":"pcoeBbm","tags":["CREATED_FROM_EOM_ACTIVITY","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545584","externalId":"REQ-545584","orderDate":"2022-05-11T18:44:51Z","requestedStartDate":"2022-05-11T18:44:51Z","lastUpdated":"2022-05-11T18:44:56.635921221Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"agreementCreation","requestSource":"eom","customerSupportModel":"Standard","businessUnit":"Retail","crdDdst":"DUEXXXX","eomActivityNumber":"3-G3VTJ1J","eomCustomerAccountNumber":"1-QH5L0","eomActivityUrlEn":"https://eom.int.bell.ca:4443/siebel/app/ecomm/enu?SWECmd=GotoView&SWEView=BEL+Activity+Detail+View&SWERF=1&SWEHo=eom.int.bell.ca&SWEBU=1&SWEApplet0=BEL+Activity+List+Applet+With+Navigation+Detail&SWERowId0=3-G3VTJ1J","eomActivityUrlFr":"https://eom.int.bell.ca:4443/siebel/app/ecomm/fra?SWECmd=GotoView&SWEView=BEL+Activity+Detail+View&SWERF=1&SWEHo=eom.int.bell.ca&SWEBU=1&SWEApplet0=BEL+Activity+List+Applet+With+Navigation+Detail&SWERowId0=3-G3VTJ1J","status":"acknowledged","product":"sipTrunk","serviceRegion":"ON","customer":{"id":"1-QH5L0","name":"Misty Cat"},"customerMarketSegment":"Ontario Enterprise","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"Agreement Creation","status":"Acknowledged","product":"SIP Trunking"}},"fr":{"source":{"requestType":"Contrat création","status":"Reçue","product":"Liaisons SIP"}}}},{"id":"bsd_REQ-545583","lastUpdated":"2022-05-11T18:44:53.507651066Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545583","status":"new","controlDesk":"businessCare","tags":["CREATED_FROM_SSC","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545583","externalId":"REQ-545583","orderDate":"2022-05-11T18:44:43Z","requestedStartDate":"2022-05-11T18:44:43Z","lastUpdated":"2022-05-11T18:44:53.506205956Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"generalInquiry-othergeneral","requestSource":"ssc","customerSupportModel":"Standard","businessUnit":"Retail","crdDdst":"NXS4A27","eomRowId":"1-3JAHZB","status":"acknowledged","product":"localLink","serviceRegion":"ON","goldenCustomer":{"id":"1004880064","email":"richard.perron@andrewpeller.com","name":"Richard Perron"},"customer":{"id":"1-3JAHZB","name":"Andrew Peller Ltd"},"creator":{"id":"richard.perron1@eportal","email":"richard.Perron@andrewpeller.com","phoneNumber":"9059219079","name":"Richard Perron"},"originator":{"id":"richard.perron1@eportal","email":"richard.Perron@andrewpeller.com","phoneNumber":"9059219079","name":"Richard Perron"},"customerMarketSegment":"Ontario Enterprise","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"General Inquiry - Other","status":"Acknowledged","product":"Other Voice Services"}},"fr":{"source":{"requestType":"Demande générale - Autre","status":"Reçue","product":"Autres services vocaux"}}}},{"id":"bsd_REQ-545582","lastUpdated":"2022-05-11T18:44:22.744411791Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545582","status":"new","controlDesk":"businessCare","tags":["CREATED_FROM_SSC","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545582","externalId":"REQ-545582","orderDate":"2022-05-11T18:44:12Z","requestedStartDate":"2022-05-11T18:44:12Z","lastUpdated":"2022-05-11T18:44:22.743087742Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"disconnect","requestSource":"ssc","customerSupportModel":"Standard","businessUnit":"Retail","existingAddress":"500 DUNDAS ST, WOODSTOCK ON, N4S 1C4, FLOOR:basement, ROOM:electrical","site":{"existing":{"address":"500 DUNDAS ST, WOODSTOCK ON, N4S 1C4, FLOOR:basement, ROOM:electrical"}},"crdDdst":"AMBMS77","eomRowId":"1-P2I-5672","status":"acknowledged","product":"businessLines","serviceRegion":"ON","requestedCompletionDate":"2022-05-16T12:00:00Z","billingAddress":"500 DUNDAS ST, WOODSTOCK ON, N4S 1C4, FLOOR:basement, ROOM:electrical","goldenCustomer":{"id":"1004699830","email":"jvarga@cityofwoodstock.ca","name":"Joanne Varga"},"customer":{"id":"1-P2I-5672","name":"The Corporation of the City Of Woodstock"},"creator":{"id":"joanne.varga@eportal","email":"jvarga@cityofwoodstock.ca","phoneNumber":"5195392382","name":"Joanne Varga"},"originator":{"id":"joanne.varga@eportal","email":"jvarga@cityofwoodstock.ca","phoneNumber":"5195392382","name":"Joanne Varga"},"customerMarketSegment":"Ontario SMB","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"Disconnect","status":"Acknowledged","product":"Business Lines"}},"fr":{"source":{"requestType":"Débrancher","status":"Reçue","product":"Lignes locales ou interurbain"}}}},{"id":"bsd_REQ-545580","lastUpdated":"2022-05-11T18:43:36.608853604Z","accessPolicyTag":["DIVISION_WIRELESS"],"workOrder":{"id":"bsd_REQ-545580","status":"new","controlDesk":"hscToronto","group":"Queue not found","tags":["CREATED_FROM_EMAIL_REQUEST","AIML_PROCESSED","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545580","externalId":"REQ-545580","emailSubject":"Corporate SIM Inquiry","orderDate":"2022-05-11T18:43:28Z","requestedStartDate":"2022-05-11T18:43:28Z","lastUpdated":"2022-05-11T18:43:36.607157652Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Wireless","incomingMailbox":"HSCToronto@bell.ca","status":"acknowledged","originator":{"email":"parag.dey@bell.ca","name":"Parag Dey"},"preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"","status":"Acknowledged"}},"fr":{"source":{"requestType":"","status":"Reçue"}}}},{"id":"bsd_REQ-545579","lastUpdated":"2022-05-11T18:43:00.783751348Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545579","status":"new","controlDesk":"managedServicesSPOA","group":"Queue not found","tags":["CREATED_FROM_EMAIL_REQUEST","AIML_PROCESSED","SMARTPATH_DISTRIBUTION_MODE_QUEUE"]},"source":{"id":"bsd_REQ-545579","externalId":"REQ-545579","emailSubject":"SR885747 - Please be advised that a new worklog has been created./ Veuillez remarquer qu\'une entrée du journal des travaux a été créée.","orderDate":"2022-05-11T18:42:56Z","requestedStartDate":"2022-05-11T18:42:56Z","lastUpdated":"2022-05-11T18:43:00.782411425Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"generalInquiry-othergeneral","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Retail","incomingMailbox":"cibcmac@bell.ca","status":"acknowledged","product":"managedServices","serviceRegion":"ON","originator":{"email":"DoNotReply-Mx@bell.ca","name":"DoNotReply-Mx@bell.ca"},"preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"General Inquiry - Other","status":"Acknowledged","product":"Managed Infrastructure Services"}},"fr":{"source":{"requestType":"Demande générale - Autre","status":"Reçue","product":"Services gérés d’infrastructure"}}}},{"id":"bsd_REQ-545578","lastUpdated":"2022-05-11T18:42:56.445464267Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545578","status":"new","controlDesk":"managedServicesSPOA","group":"Queue not found","tags":["CREATED_FROM_EMAIL_REQUEST","AIML_PROCESSED","SMARTPATH_DISTRIBUTION_MODE_QUEUE","AIML_LOW_SCORE"]},"source":{"id":"bsd_REQ-545578","externalId":"REQ-545578","emailSubject":"RITM0206670 - TASK0578230 - Cabling","orderDate":"2022-05-11T18:42:52Z","requestedStartDate":"2022-05-11T18:42:52Z","lastUpdated":"2022-05-11T18:42:56.443613172Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"generalInquiry-othergeneral","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Retail","incomingMailbox":"aircanada.mscc@bell.ca","status":"acknowledged","product":"managedServices","serviceRegion":"ON","originator":{"email":"r.di_stefano@bell.ca","name":"Rosie Di Stefano"},"preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"General Inquiry - Other","status":"Acknowledged","product":"Managed Infrastructure Services"}},"fr":{"source":{"requestType":"Demande générale - Autre","status":"Reçue","product":"Services gérés d’infrastructure"}}}},{"id":"bsd_REQ-545577","lastUpdated":"2022-05-11T18:42:27.177771792Z","accessPolicyTag":["DIVISION_WHOLESALE"],"workOrder":{"id":"bsd_REQ-545577","status":"new","controlDesk":"wholesaleVoice","group":"Wholesale Voice","tags":["CREATED_FROM_EMAIL_REQUEST","AIML_PROCESSED","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545577","externalId":"REQ-545577","emailSubject":"[EXT]Order-PON637620-Culligan Water Conditioning-Aurora-Calling Card","orderDate":"2022-05-11T18:42:18Z","requestedStartDate":"2022-05-11T18:42:18Z","lastUpdated":"2022-05-11T18:42:27.169492071Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"change","requestSource":"email","customerSupportModel":"Non-Standard","businessUnit":"Wholesale","incomingMailbox":"telizon@bell.ca","crdDdst":"CRER92U","status":"acknowledged","product":"businessLines","serviceRegion":"ON","goldenCustomer":{"id":"1004930980","name":"Telizon Inc."},"customer":{"name":"Telizon Inc."},"originator":{"email":"alucas@telizon.ca","name":"Andrea Lucas"},"customerMarketSegment":"Carrier Services OR","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"requestType":"Change","status":"Acknowledged","product":"Business Lines"}},"fr":{"source":{"requestType":"Modifier","status":"Reçue","product":"Lignes locales ou interurbain"}}}},{"id":"bsd_REQ-545576","lastUpdated":"2022-05-11T18:42:15.212759903Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545576","status":"new","controlDesk":"businessCare","tags":["CREATED_FROM_SSC","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545576","externalId":"REQ-545576","orderDate":"2022-05-11T18:42:04Z","requestedStartDate":"2022-05-11T18:42:04Z","lastUpdated":"2022-05-11T18:42:15.2112101Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"disconnect","requestSource":"ssc","billingAccount":"507532514","customerSupportModel":"Non-Standard","businessUnit":"Retail","existingAddress":"565 LANGFORD BLVD, BRADFORD ON, L3Z 0C1, FLOOR:n/a, ROOM:n/a","site":{"existing":{"address":"565 LANGFORD BLVD, BRADFORD ON, L3Z 0C1, FLOOR:n/a, ROOM:n/a"}},"crdDdst":"GTRGBDM","eomRowId":"1-7ZO-992","status":"acknowledged","product":"businessInternet","serviceRegion":"ON","requestedCompletionDate":"2022-05-12T12:00:00Z","billingAddress":"1600 BOUL SAINT-MARTIN E, LAVAL QC, H7G 4S7, FLOOR:Tour B, bureau 300","goldenCustomer":{"id":"1004998244","email":"activitessupporttelecom@metro.ca","name":"Metro Richelieu"},"customer":{"id":"1-7ZO-992","name":"Métro Richelieu Inc."},"creator":{"id":"activites.support@eportal","email":"activitessupporttelecom@metro.ca","phoneNumber":"4506623300","name":"Metro Richelieu"},"originator":{"id":"activites.support@eportal","email":"activitessupporttelecom@metro.ca","phoneNumber":"4506623300","name":"Metro Richelieu"},"customerMarketSegment":"Quebec Enterprise","preferredLanguage":"fr"},"fullTextSearch":{"en":{"source":{"requestType":"Disconnect","status":"Acknowledged","product":"Business Internet"}},"fr":{"source":{"requestType":"Débrancher","status":"Reçue","product":"Internet d\'affaires"}}}},{"id":"bsd_REQ-545575","lastUpdated":"2022-05-11T18:41:47.55494603Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545575","status":"new","controlDesk":"businessCare","group":"Email - Enterprise - Atlantic","tags":["CREATED_FROM_EMAIL_REQUEST","SMARTPATH_DISTRIBUTION_MODE_QUEUE"]},"source":{"id":"bsd_REQ-545575","externalId":"REQ-545575","emailSubject":"[EXT]Activate 506-848-5901","orderDate":"2022-05-11T18:41:42Z","requestedStartDate":"2022-05-11T18:41:42Z","lastUpdated":"2022-05-11T18:41:47.55379682Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Retail","incomingMailbox":"Atlanticenterprise@bellaliant.ca","status":"acknowledged","serviceRegion":"EAST","originator":{"email":"slevesque@quispamsis.ca","name":"Sherri Levesque"},"customerMarketSegment":"Bell Atlantic","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"status":"Acknowledged"}},"fr":{"source":{"status":"Reçue"}}}},{"id":"bsd_REQ-545574","lastUpdated":"2022-05-11T18:44:41.643131618Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545574","status":"customerReplied","controlDesk":"businessCare","group":"Atlantic Email - RETAIL DATA","tags":["CREATED_FROM_EMAIL_REQUEST","SMARTPATH_DISTRIBUTION_MODE_QUEUE"]},"source":{"id":"bsd_REQ-545574","externalId":"REQ-545574","emailSubject":"Medium Business (REMOVE) Order for Guardian Transfer & Storage - Reference # : HS-27825","orderDate":"2022-05-11T18:41:38Z","requestedStartDate":"2022-05-11T18:41:38Z","lastUpdated":"2022-05-11T18:44:41.641305676Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestSource":"email","customerSupportModel":"Standard","businessUnit":"Retail","incomingMailbox":"Datagroup@bellaliant.ca","status":"inProgress","serviceRegion":"EAST","originator":{"email":"steve.spicer@bellaliant.ca","name":"Steven Spicer"},"customerMarketSegment":"Bell Atlantic","preferredLanguage":"en"},"fullTextSearch":{"en":{"source":{"status":"In progress"}},"fr":{"source":{"status":"En cours"}}}},{"id":"bsd_REQ-545573","lastUpdated":"2022-05-11T18:41:26.572076467Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545573","status":"new","controlDesk":"businessCare","tags":["SMARTPATH_COPY","SMARTPATH_DISTRIBUTION_MODE_FILTER","CREATED_FROM_SMARTPATH","COPIED_FROM_SMARTPATH"]},"source":{"id":"bsd_REQ-545573","externalId":"REQ-545573","orderDate":"2022-05-11T18:41:19Z","requestedStartDate":"2022-05-03T12:13:06Z","lastUpdated":"2022-05-11T18:41:26.570318027Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"coaching","requestSource":"smartpath","customerSupportModel":"Standard","businessUnit":"Retail","existingAddress":"","siteA":"","site":{"existing":{"address":""},"installation":{"address":""}},"crdDdst":"AMBPB42","status":"acknowledged","product":"ipvpn","serviceRegion":"ON","billingAddress":"","goldenCustomer":{"id":"1004694547","name":"Diversicare Canada Management Services Company Inc."},"customer":{"name":"Diversicare Canada Management Services Company Inc."},"creator":{"id":"bccs.3005818","email":"noel.stewart@bell.ca","name":"Noel Stewart"},"originator":{"email":"korazati@bell.ca","phoneNumber":"(905) 614-6014","name":"El-Korazati, Mohammed","type":""},"customerMarketSegment":"Ontario SMB","preferredLanguage":"en","relatedOrder":[{"id":"bsd_REQ-530389","sourceSystemId":"BSD","relationType":"origin"}]},"fullTextSearch":{"en":{"source":{"requestType":"Coaching","status":"Acknowledged","product":"IP VPN"}},"fr":{"source":{"requestType":"Coaching","status":"Reçue","product":"RPV IP"}}}},{"id":"bsd_REQ-545571","lastUpdated":"2022-05-11T18:41:07.356342043Z","accessPolicyTag":["DIVISION_RETAIL"],"workOrder":{"id":"bsd_REQ-545571","status":"new","controlDesk":"businessCare","tags":["CREATED_FROM_SSC","SMARTPATH_DISTRIBUTION_MODE_FILTER"]},"source":{"id":"bsd_REQ-545571","externalId":"REQ-545571","orderDate":"2022-05-11T18:40:56Z","requestedStartDate":"2022-05-11T18:40:56Z","lastUpdated":"2022-05-11T18:41:07.354520095Z","referredType":"ServiceOrder","sourceSystemId":"BSD","requestType":"generalInquiry-accountcontractupdate","requestSource":"ssc","customerSupportModel":"Standard","businessUnit":"Retail","crdDdst":"NXT4GOR","eomRowId":

In [129]:
r_dict = json.loads(r.text)

In [130]:
meta_data = r_dict['metadata']
results = r_dict['results']

In [131]:
len(results)

500

In [132]:
meta_data

{'offset': 0, 'limit': 500, 'totalRecordCount': 18256}

In [136]:

results[5]['workOrder']['status']

'new'

In [6]:
f = open('../tests/dummy_smartpath_response.json')
r_dict = json.load(f)
results = r_dict['results']

In [68]:
def nested_col_nans_to_dict(results, nested_cols):
    """For each flattened field, we cannot use 'nan' values when there is no data. If there is no data
    for a flattened field, we must represent the fact that there is no data by a dictionary"""

    for resp in results:
        for nested_col in nested_cols:
            if nested_col not in resp.keys():
                resp.update({nested_col: {"value": "no-data"}})
    return results

Current project environment: PROD
Current SP environment: PROD
https://operationcentre.ms.bell.ca
845e3004-c0f2-41c7-845f-2dd89481c842

In [69]:
def prepare_data_for_elastic(results, all_cols):
    """
    1. Make custom nan values for flattened fields for indexation puposes
    2. Append foc targets to API results
    3. Then create a dataframe that is converted to a list of dicts. This format is
    requred for Elasticsearch indexation. Each dictionnary will become an Elastci doc"""

    # 1
    results = nested_col_nans_to_dict(results, nested_cols)

    # 2
    # con = sqlite3.connect(database)
    # cur = con.cursor()
    
    con = pyodbc.connect('DRIVER={ODBC Driver 17 for SQL Server};SERVER='+SQL_SERVER+';DATABASE='+DATABASE+';UID='+SQL_USER+';PWD='+SQL_PASS)
    cur = con.cursor()

    for res in results:
        foc_target = get_foc_target(cur, res)
        res['source']['focTarget'] = foc_target
        res['request_id'] = res['id']
        # res['lastUpdated'] = res['lastUpdated'].replace('Z', ' ')
        # res['lastUpdated'] = res['lastUpdated'][:-1] + 'Z'
        del res['id']

    # 3
    df = pd.DataFrame(data=results, columns=all_cols)
    df = df.fillna('nan')

    return df.to_dict('records')

In [70]:
def get_foc_target(cur, res):
    """Assumption: if either of the columns to retrieve an foc target from the db is None,
    we assume the foctarget is 0"""

    sql_query_values = {}
    for col in ['requestSource', 'product', 'serviceRegion', 'requestType']:
        if col in res['source'].keys():
            sql_query_values[col] = res['source'][col].lower()
        else:
            sql_query_values[col] = None

    if not all(
        (isinstance(sql_query_values['requestSource'], str),
         isinstance(sql_query_values['product'], str),
         isinstance(sql_query_values['serviceRegion'], str),
         isinstance(sql_query_values['requestType'], str))
         ):
        return 0

    sql = f"""SELECT CASE WHEN foc_target IS NULL THEN 0 ELSE foc_target 
             END as focTarget FROM {DB.foc_targets()}
    WHERE request_source='""" + sql_query_values['requestSource'] + """'
    AND product='""" + sql_query_values['product'] + """'
    AND service_region='""" + sql_query_values['serviceRegion'] + """'
    AND request_type='""" + sql_query_values['requestType'] + "'"

    foc_target = cur.execute(sql).fetchall()
    
    if not foc_target:
        return 0
    return foc_target[0][0]

In [71]:
df_dict = prepare_data_for_elastic(results, all_cols)

In [72]:
df_dict

[{'request_id': 'bsd_REQ-544756',
  'lastUpdated': '2022-05-11T15:26:36.538190233Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544756',
   'status': 'inProgress',
   'controlDesk': 'bbscL1',
   'assignee': {'id': 'ba0cdrq', 'name': 'Marc Larivee'},
   'tags': ['CREATED_FROM_SMARTPATH', 'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
  'source': {'id': 'bsd_REQ-544756',
   'externalId': 'REQ-544756',
   'orderDate': '2022-05-11T15:26:28Z',
   'requestedStartDate': '2022-05-11T15:26:28Z',
   'startDate': '2022-05-11T15:26:33.226889392Z',
   'lastUpdated': '2022-05-11T15:26:36.536276519Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'change',
   'requestSource': 'smartpath',
   'billingAccount': '506155943',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'crdDdst': 'AAO3377',
   'status': 'inProgress',
   'product': 'businessInternet',
   'serviceRegion': 'ON',
   'goldenCustomer': {'id': '1004996774',
    'name': 'Eurofins Enviroment Testing Canada'},
   'customer': {'name': 'Eurofins Enviroment Testing Canada'},
   'creator': {'id': 'ba0cdrq',
    'email': 'marc.larivee@bell.ca',
    'name': 'Marc Larivee'},
   'originator': {'email': 'steven.tosh@et.eurofinsca.com',
    'phoneNumber': '9056808887',
    'name': 'Steven Tosh'},
   'customerMarketSegment': 'Ontario SMB - Mass',
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544755',
  'lastUpdated': '2022-05-11T15:26:31.453582272Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544755',
   'status': 'inProgress',
   'controlDesk': 'bbscAtlantic',
   'assignee': {'id': 'ca66918', 'name': 'Carolyn Glanville'},
   'tags': ['CREATED_FROM_SMARTPATH', 'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
  'source': {'id': 'bsd_REQ-544755',
   'externalId': 'REQ-544755',
   'orderDate': '2022-05-11T15:26:23Z',
   'requestedStartDate': '2022-05-11T15:26:23Z',
   'startDate': '2022-05-11T15:26:28.061414586Z',
   'lastUpdated': '2022-05-11T15:26:31.451897312Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'billingInquiry-copyofinvoice',
   'requestSource': 'smartpath',
   'billingAccount': '',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'status': 'inProgress',
   'product': 'businessLines',
   'serviceRegion': 'NB',
   'goldenCustomer': {'id': '1008424399',
    'name': 'The Salvation Army - Richmond hill'},
   'customer': {'name': 'The Salvation Army - Richmond hill'},
   'creator': {'id': 'ca66918',
    'email': 'Carolyn.Glanville@bellaliant.ca',
    'name': 'Carolyn Glanville'},
   'originator': {'email': 'loretta.elderkin@salvationarmy.ca',
    'phoneNumber': '5063872012',
    'name': 'Loretta Elderkin'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544754',
  'lastUpdated': '2022-05-11T15:26:22.173278074Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544754',
   'status': 'new',
   'controlDesk': 'businessCare',
   'group': 'Atlantic Email - RETAIL DATA',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE']},
  'source': {'id': 'bsd_REQ-544754',
   'externalId': 'REQ-544754',
   'emailSubject': '[EXT]RE: Regarding your Bell request # REQ-537166',
   'orderDate': '2022-05-11T15:26:17Z',
   'requestedStartDate': '2022-05-11T15:26:17Z',
   'lastUpdated': '2022-05-11T15:26:22.171894309Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'incomingMailbox': 'Datagroup@bellaliant.ca',
   'status': 'acknowledged',
   'serviceRegion': 'EAST',
   'originator': {'email': 'dgritten@maritimebeauty.com',
    'name': 'Dave Gritten'},
   'customerMarketSegment': 'Bell Atlantic',
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544753',
  'lastUpdated': '2022-05-11T15:26:20.24066539Z',
  'accessPolicyTag': ['DIVISION_WIRELESS'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544753',
   'status': 'inProgress',
   'controlDesk': 'wirelessBBSC',
   'assignee': {'id': 'sa6101851', 'name': 'Saamiyah Jambocus'},
   'tags': ['CREATED_FROM_SMARTPATH', 'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
  'source': {'id': 'bsd_REQ-544753',
   'externalId': 'REQ-544753',
   'orderDate': '2022-05-11T15:26:12Z',
   'requestedStartDate': '2022-05-11T15:26:12Z',
   'startDate': '2022-05-11T15:26:17.070258002Z',
   'lastUpdated': '2022-05-11T15:26:20.239549909Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'changeSIM',
   'requestSource': 'smartpath',
   'billingAccount': '',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Wireless',
   'crdDdst': 'AAWSPUL',
   'status': 'inProgress',
   'product': 'corporateHardwareOrders',
   'serviceRegion': 'ON',
   'goldenCustomer': {'id': '1005534579', 'name': 'Avante Concrete Ltd.'},
   'customer': {'name': 'Avante Concrete Ltd.'},
   'creator': {'id': 'sa6101851',
    'email': 'saamiyah.jambocus@bell.ca',
    'name': 'Saamiyah Jambocus'},
   'originator': {'email': '',
    'phoneNumber': '6046444042',
    'name': 'PAULA Freeman',
    'type': 'authorizedContact'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544752',
  'lastUpdated': '2022-05-11T15:26:04.321788662Z',
  'accessPolicyTag': ['DIVISION_WIRELESS'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544752',
   'status': 'new',
   'controlDesk': 'hscOttawa',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
  'source': {'id': 'bsd_REQ-544752',
   'externalId': 'REQ-544752',
   'emailSubject': '[EXT]Re: [EXT]Re: Keystone Automotive Industries Inc. (T1046) - Order Confirmation: #2449309 REQ-544147',
   'orderDate': '2022-05-11T15:25:59Z',
   'requestedStartDate': '2022-05-11T15:25:59Z',
   'lastUpdated': '2022-05-11T15:26:04.320418257Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Wireless',
   'incomingMailbox': 'HSCOttawa@bell.ca',
   'status': 'acknowledged',
   'originator': {'email': 'cbiorders@cbitelecom.com', 'name': 'Orders'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544751',
  'lastUpdated': '2022-05-11T15:26:00.254716147Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544751',
   'status': 'new',
   'controlDesk': 'customBilling',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE',
    'AIML_LOW_SCORE']},
  'source': {'id': 'bsd_REQ-544751',
   'externalId': 'REQ-544751',
   'emailSubject': '[EXT]ajout ou modification',
   'orderDate': '2022-05-11T15:25:51Z',
   'requestedStartDate': '2022-05-11T15:25:51Z',
   'lastUpdated': '2022-05-11T15:26:00.252830031Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'change',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'incomingMailbox': 'facturation_en_ligne@bell.ca',
   'crdDdst': 'CALRADT',
   'status': 'acknowledged',
   'product': 'businessLines',
   'serviceRegion': 'QC',
   'goldenCustomer': {'id': '1005182713',
    'name': 'ADT Security Services Canada Inc.'},
   'customer': {'name': 'ADT Security Services Canada Inc.'},
   'originator': {'email': 'marie-andree.poirier1@telus.com',
    'name': 'Marie-Andree Poirier'},
   'preferredLanguage': 'fr',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544750',
  'lastUpdated': '2022-05-11T15:25:52.92737668Z',
  'accessPolicyTag': ['DIVISION_WHOLESALE', 'EMAIL_TRUNKSIDE'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544750',
   'status': 'new',
   'controlDesk': 'trunkside',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE',
    'AIML_LOW_SCORE']},
  'source': {'id': 'bsd_REQ-544750',
   'externalId': 'REQ-544750',
   'emailSubject': '[EXT]AASR TTO216903 Toronto 5ESS Decommissioning',
   'orderDate': '2022-05-11T15:25:43Z',
   'requestedStartDate': '2022-05-11T15:25:43Z',
   'lastUpdated': '2022-05-11T15:25:52.925858463Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'disconnect',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Wholesale',
   'incomingMailbox': 'trunkside.orders@bell.ca',
   'crdDdst': 'CLER996',
   'status': 'acknowledged',
   'product': 'businessLines',
   'serviceRegion': 'ON',
   'goldenCustomer': {'id': '1004932488', 'name': 'TELUS Communications Inc.'},
   'customer': {'name': 'TELUS Communications Inc.'},
   'originator': {'email': 'TrunksideAB@TELUS.COM', 'name': 'Trunkside (AB)'},
   'customerMarketSegment': 'Carrier Services OR',
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544749',
  'lastUpdated': '2022-05-11T15:25:44.730818625Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544749',
   'status': 'redistribute',
   'controlDesk': 'businessCare',
   'tags': ['CREATED_FROM_SMARTPATH', 'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
  'source': {'id': 'bsd_REQ-544749',
   'externalId': 'REQ-544749',
   'orderDate': '2022-05-11T15:25:38Z',
   'requestedStartDate': '2022-05-11T15:25:38Z',
   'lastUpdated': '2022-05-11T15:25:44.729003168Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'serviceAssurance',
   'requestSource': 'smartpath',
   'billingAccount': '',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'crdDdst': 'ALQNB64',
   'status': 'inProgress',
   'product': 'sipTrunk',
   'serviceRegion': 'QC',
   'goldenCustomer': {'id': '1004698409', 'name': 'Polycor Inc.'},
   'customer': {'name': 'Polycor Inc.'},
   'creator': {'id': 'mylene.hebert',
    'email': 'mylene.hebert@bell.ca',
    'name': 'Mylene Hebert'},
   'originator': {'email': 'andre.breton@polycor.com',
    'phoneNumber': '819.652.2000 x4257 ',
    'name': 'Andre Breton '},
   'customerMarketSegment': 'Quebec SMB',
   'preferredLanguage': 'fr',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544748',
  'lastUpdated': '2022-05-11T15:25:19.296295065Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544748',
   'status': 'new',
   'controlDesk': 'specialEvents',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE',
    'AIML_LOW_SCORE']},
  'source': {'id': 'bsd_REQ-544748',
   'externalId': 'REQ-544748',
   'emailSubject': '[EXT] Demande de soumission - branchement de modem haute vitesse temporaire, Conférence de presse du ministre Steven Guilbeaut,',
   'orderDate': '2022-05-11T15:25:10Z',
   'requestedStartDate': '2022-05-11T15:25:10Z',
   'lastUpdated': '2022-05-11T15:25:19.294539735Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'add',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'incomingMailbox': 'evenements.speciaux@bell.ca',
   'status': 'acknowledged',
   'product': 'businessInternet',
   'serviceRegion': 'QC',
   'originator': {'email': 'Marie-Pier.Dostie@ec.gc.ca',
    'name': 'Marie-Pier [ECCC] Dostie'},
   'preferredLanguage': 'fr',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544747',
  'lastUpdated': '2022-05-11T15:25:10.156445654Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544747',
   'status': 'new',
   'controlDesk': 'managedServicesSPOA',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE']},
  'source': {'id': 'bsd_REQ-544747',
   'externalId': 'REQ-544747',
   'emailSubject': 'Please be advised that SR885774 is complete.  A task is pending that requires your attention./Veuillez prendre note que SR885774 a été exécutée.  Une tâche est en attente qui requiert votre attention.',
   'orderDate': '2022-05-11T15:25:05Z',
   'requestedStartDate': '2022-05-11T15:25:05Z',
   'lastUpdated': '2022-05-11T15:25:10.154872783Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'generalInquiry-othergeneral',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'incomingMailbox': 'cibcmac@bell.ca',
   'status': 'acknowledged',
   'product': 'managedServices',
   'serviceRegion': 'ON',
   'originator': {'email': 'DoNotReply-Mx@bell.ca',
    'name': 'DoNotReply-Mx@bell.ca'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544746',
  'lastUpdated': '2022-05-11T15:25:06.327495583Z',
  'accessPolicyTag': ['DIVISION_WHOLESALE'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544746',
   'status': 'new',
   'controlDesk': 'localMigration',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE']},
  'source': {'id': 'bsd_REQ-544746',
   'externalId': 'REQ-544746',
   'emailSubject': 'RE: 4164293888(202), 535681245 CCTS 1217100A COMPLAINT Ning An',
   'orderDate': '2022-05-11T15:24:57Z',
   'requestedStartDate': '2022-05-11T15:24:57Z',
   'lastUpdated': '2022-05-11T15:25:06.326097082Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'generalInquiry-othergeneral',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Wholesale',
   'incomingMailbox': 'csglmu@bell.ca',
   'status': 'acknowledged',
   'product': 'businessLines',
   'serviceRegion': 'ON',
   'originator': {'email': 'christopher.lamontagne@bell.ca',
    'name': 'Christopher Lamontagne'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},
  'SearchFilter': {'value': 'no-data'},
  'AttributeFilter': {'value': 'no-data'},
  'AlwaysRejectFilter': {'value': 'no-data'},
  'FilterOperator': {'value': 'no-data'},
  'FilterGroup': {'value': 'no-data'},
  'FilterGroupOperator': {'value': 'no-data'},
  'FilterGroupModifier': {'value': 'no-data'}},
 {'request_id': 'bsd_REQ-544745',
  'lastUpdated': '2022-05-11T15:24:56.409612864Z',
  'accessPolicyTag': ['DIVISION_RETAIL'],
  'OrderResponse': {'value': 'no-data'},
  'workOrder': {'id': 'bsd_REQ-544745',
   'status': 'new',
   'controlDesk': 'managedServicesSPOA',
   'group': 'Queue not found',
   'tags': ['CREATED_FROM_EMAIL_REQUEST',
    'AIML_PROCESSED',
    'SMARTPATH_DISTRIBUTION_MODE_QUEUE']},
  'source': {'id': 'bsd_REQ-544745',
   'externalId': 'REQ-544745',
   'emailSubject': "SR885774 - Please be advised that a new worklog has been created./ Veuillez remarquer qu'une entrée du journal des travaux a été créée.",
   'orderDate': '2022-05-11T15:24:51Z',
   'requestedStartDate': '2022-05-11T15:24:51Z',
   'lastUpdated': '2022-05-11T15:24:56.408254842Z',
   'referredType': 'ServiceOrder',
   'sourceSystemId': 'BSD',
   'requestType': 'generalInquiry-othergeneral',
   'requestSource': 'email',
   'customerSupportModel': 'Standard',
   'businessUnit': 'Retail',
   'incomingMailbox': 'cibcmac@bell.ca',
   'status': 'acknowledged',
   'product': 'managedServices',
   'serviceRegion': 'ON',
   'originator': {'email': 'DoNotReply-Mx@bell.ca',
    'name': 'DoNotReply-Mx@bell.ca'},
   'preferredLanguage': 'en',
   'focTarget': 0},
  'OrderRelatedParty': {'value': 'no-data'},
  'SearchDetails': {'value': 'no-data'},

### Flattened

In [73]:

def initialize_elastic_connection():
    
    es_connection = Elasticsearch('https://paas-mtrl-blmcih-data-03.qc.bell.ca:9200/', 
                                  verify_certs = False,
                                  http_auth=('svc-bbm_aiml-user', 'v^*SRFP%uBM2v2bs9VG'))
    return es_connection

In [74]:
def elastic_data_generator(df, cols, index_name):
    for c, line in enumerate(df):
        yield {
          '_op_type': 'index',
          '_index': index_name,
          '_id': line.get('id'),
          'type': '_doc',
          '_source': 
            {k: line.get(k, ['No Data']) for k in cols}
        }

In [75]:
def create_index(es_connection, index_name):
    es_connection.indices.create(index=index_name, body=mappings)

In [76]:
def load_data_to_index(es_connection, df_dict, cols, index_name):
    
    if not df_dict:
        print("Empty dict - Nothing was indexed")
        return
    else:
        try:
            resp = helpers.bulk(es_connection, elastic_data_generator(df_dict, cols, index_name))
            print("finished uploading data")
        except Exception as e:
            print(e)

In [77]:
es_connection = initialize_elastic_connection()

In [79]:
load_data_to_index(es_connection, df_dict, all_cols, 'bbm_aiml_stm_test_prod_3')

C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

finished uploading data

### Initialize Elastic index

In [137]:
es_connection = initialize_elastic_connection()
create_index(es_connection, 'bbm_aiml_stm_prod_v2')

C:\Users\ez99152\AppData\Local\Temp/ipykernel_13772/1666395428.py:2: DeprecationWarning: The 'body' parameter is deprecated for the 'create' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  es_connection.indices.create(index=index_name, body=mappings)
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\ez99152\AppData\Local\Temp/ipykernel_13772/1666395428.py:2: ElasticsearchWarning: The client is unable to verify that the server is Elasticsearch due security privileges on the server side
  es_connection.indices.create(index=index_name, body=mappings)
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

## Query the data

In [29]:
q = {
    "fields": [
        "request_id",
        "accessPolicyTag",
        "workOrder.status",
        "workOrder.followUpDate",
        "workOrder.controlDesk",
        "workOrder.group ",
        "workOrder.assignee",
        "workOrder.tags",
        "source.orderDate",
        "source.requestedStartDate",
        "source.requestType",
        "source.requestSource",
        "source.customerSupportModel",
        "source.businessUnit",
        "source.status",
        "source.product",
        "source.serviceRegion",
        "source.goldenCustomer",
        "source.customer",
        "source.customerMarketSegment",
        "source.preferredLanguage",
        "source.focTarget"
  ]
}

In [50]:
q = make_elastic_query("2022-04-27T10:20:55")

In [80]:
r = es_connection.search(body=q, index='bbm_aiml_stm_test_prod_3', size=4000)

C:\Users\ez99152\AppData\Local\Temp/ipykernel_13772/793927149.py:1: DeprecationWarning: The 'body' parameter is deprecated for the 'search' API and will be removed in a future version. Instead use API parameters directly. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  r = es_connection.search(body=q, index='bbm_aiml_stm_test_prod_3', size=4000)
C:\Users\ez99152\Anaconda3\envs\ocdp-tti-ddp\lib\site-packages\urllib3\connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'paas-mtrl-blmcih-data-03.qc.bell.ca'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [81]:
r

{'took': 98,
 'timed_out': False,
 '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0},
 'hits': {'total': {'value': 260, 'relation': 'eq'},
  'max_score': 2.01131,
  'hits': [{'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'Fb-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544756',
     'lastUpdated': '2022-05-11T15:26:36.538190233Z',
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544756',
      'status': 'inProgress',
      'controlDesk': 'bbscL1',
      'assignee': {'id': 'ba0cdrq', 'name': 'Marc Larivee'},
      'tags': ['CREATED_FROM_SMARTPATH',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544756',
      'externalId': 'REQ-544756',
      'orderDate': '2022-05-11T15:26:28Z',
      'requestedStartDate': '2022-05-11T15:26:28Z',
      'startDate': '2022-05-11T15:26:33.226889392Z',
      'lastUpdated': '2022-05-11T15:26:36.536276519Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'change',
      'requestSource': 'smartpath',
      'billingAccount': '506155943',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Retail',
      'crdDdst': 'AAO3377',
      'status': 'inProgress',
      'product': 'businessInternet',
      'serviceRegion': 'ON',
      'goldenCustomer': {'id': '1004996774',
       'name': 'Eurofins Enviroment Testing Canada'},
      'customer': {'name': 'Eurofins Enviroment Testing Canada'},
      'creator': {'id': 'ba0cdrq',
       'email': 'marc.larivee@bell.ca',
       'name': 'Marc Larivee'},
      'originator': {'email': 'steven.tosh@et.eurofinsca.com',
       'phoneNumber': '9056808887',
       'name': 'Steven Tosh'},
      'customerMarketSegment': 'Ontario SMB - Mass',
      'preferredLanguage': 'en',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customer': [{'name': 'Eurofins Enviroment Testing Canada'}],
     'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'workOrder.status': ['inProgress'],
     'source.orderDate': ['2022-05-11T15:26:28Z'],
     'source.requestType': ['change'],
     'source.goldenCustomer': [{'name': 'Eurofins Enviroment Testing Canada',
       'id': '1004996774'}],
     'source.focTarget': [0],
     'source.requestSource': ['smartpath'],
     'workOrder.controlDesk': ['bbscL1'],
     'source.customerMarketSegment': ['Ontario SMB - Mass'],
     'lastUpdated': ['2022-05-11 15:26:36.53800+0000'],
     'source.status': ['inProgress'],
     'source.serviceRegion': ['ON'],
     'source.requestedStartDate': ['2022-05-11T15:26:28Z'],
     'source.preferredLanguage': ['en'],
     'source.businessUnit': ['Retail'],
     'workOrder.tags': ['CREATED_FROM_SMARTPATH',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
     'request_id': ['bsd_REQ-544756'],
     'workOrder.assignee': [{'name': 'Marc Larivee', 'id': 'ba0cdrq'}],
     'source.product': ['businessInternet']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'Fr-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544755',
     'lastUpdated': '2022-05-11T15:26:31.453582272Z',
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544755',
      'status': 'inProgress',
      'controlDesk': 'bbscAtlantic',
      'assignee': {'id': 'ca66918', 'name': 'Carolyn Glanville'},
      'tags': ['CREATED_FROM_SMARTPATH',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544755',
      'externalId': 'REQ-544755',
      'orderDate': '2022-05-11T15:26:23Z',
      'requestedStartDate': '2022-05-11T15:26:23Z',
      'startDate': '2022-05-11T15:26:28.061414586Z',
      'lastUpdated': '2022-05-11T15:26:31.451897312Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'billingInquiry-copyofinvoice',
      'requestSource': 'smartpath',
      'billingAccount': '',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Retail',
      'status': 'inProgress',
      'product': 'businessLines',
      'serviceRegion': 'NB',
      'goldenCustomer': {'id': '1008424399',
       'name': 'The Salvation Army - Richmond hill'},
      'customer': {'name': 'The Salvation Army - Richmond hill'},
      'creator': {'id': 'ca66918',
       'email': 'Carolyn.Glanville@bellaliant.ca',
       'name': 'Carolyn Glanville'},
      'originator': {'email': 'loretta.elderkin@salvationarmy.ca',
       'phoneNumber': '5063872012',
       'name': 'Loretta Elderkin'},
      'preferredLanguage': 'en',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customer': [{'name': 'The Salvation Army - Richmond hill'}],
     'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'workOrder.status': ['inProgress'],
     'source.orderDate': ['2022-05-11T15:26:23Z'],
     'source.requestType': ['billingInquiry-copyofinvoice'],
     'source.goldenCustomer': [{'name': 'The Salvation Army - Richmond hill',
       'id': '1008424399'}],
     'source.focTarget': [0],
     'source.requestSource': ['smartpath'],
     'workOrder.controlDesk': ['bbscAtlantic'],
     'lastUpdated': ['2022-05-11 15:26:31.45300+0000'],
     'source.status': ['inProgress'],
     'source.serviceRegion': ['NB'],
     'source.requestedStartDate': ['2022-05-11T15:26:23Z'],
     'source.preferredLanguage': ['en'],
     'source.businessUnit': ['Retail'],
     'workOrder.tags': ['CREATED_FROM_SMARTPATH',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
     'request_id': ['bsd_REQ-544755'],
     'workOrder.assignee': [{'name': 'Carolyn Glanville', 'id': 'ca66918'}],
     'source.product': ['businessLines']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'GL-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544753',
     'lastUpdated': '2022-05-11T15:26:20.24066539Z',
     'accessPolicyTag': ['DIVISION_WIRELESS'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544753',
      'status': 'inProgress',
      'controlDesk': 'wirelessBBSC',
      'assignee': {'id': 'sa6101851', 'name': 'Saamiyah Jambocus'},
      'tags': ['CREATED_FROM_SMARTPATH',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544753',
      'externalId': 'REQ-544753',
      'orderDate': '2022-05-11T15:26:12Z',
      'requestedStartDate': '2022-05-11T15:26:12Z',
      'startDate': '2022-05-11T15:26:17.070258002Z',
      'lastUpdated': '2022-05-11T15:26:20.239549909Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'changeSIM',
      'requestSource': 'smartpath',
      'billingAccount': '',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Wireless',
      'crdDdst': 'AAWSPUL',
      'status': 'inProgress',
      'product': 'corporateHardwareOrders',
      'serviceRegion': 'ON',
      'goldenCustomer': {'id': '1005534579', 'name': 'Avante Concrete Ltd.'},
      'customer': {'name': 'Avante Concrete Ltd.'},
      'creator': {'id': 'sa6101851',
       'email': 'saamiyah.jambocus@bell.ca',
       'name': 'Saamiyah Jambocus'},
      'originator': {'email': '',
       'phoneNumber': '6046444042',
       'name': 'PAULA Freeman',
       'type': 'authorizedContact'},
      'preferredLanguage': 'en',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customer': [{'name': 'Avante Concrete Ltd.'}],
     'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_WIRELESS'],
     'workOrder.status': ['inProgress'],
     'source.orderDate': ['2022-05-11T15:26:12Z'],
     'source.requestType': ['changeSIM'],
     'source.goldenCustomer': [{'name': 'Avante Concrete Ltd.',
       'id': '1005534579'}],
     'source.focTarget': [0],
     'source.requestSource': ['smartpath'],
     'workOrder.controlDesk': ['wirelessBBSC'],
     'lastUpdated': ['2022-05-11 15:26:20.24000+0000'],
     'source.status': ['inProgress'],
     'source.serviceRegion': ['ON'],
     'source.requestedStartDate': ['2022-05-11T15:26:12Z'],
     'source.preferredLanguage': ['en'],
     'source.businessUnit': ['Wireless'],
     'workOrder.tags': ['CREATED_FROM_SMARTPATH',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
     'request_id': ['bsd_REQ-544753'],
     'workOrder.assignee': [{'name': 'Saamiyah Jambocus', 'id': 'sa6101851'}],
     'source.product': ['corporateHardwareOrders']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'Gb-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544752',
     'lastUpdated': '2022-05-11T15:26:04.321788662Z',
     'accessPolicyTag': ['DIVISION_WIRELESS'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544752',
      'status': 'new',
      'controlDesk': 'hscOttawa',
      'group': 'Queue not found',
      'tags': ['CREATED_FROM_EMAIL_REQUEST',
       'AIML_PROCESSED',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544752',
      'externalId': 'REQ-544752',
      'emailSubject': '[EXT]Re: [EXT]Re: Keystone Automotive Industries Inc. (T1046) - Order Confirmation: #2449309 REQ-544147',
      'orderDate': '2022-05-11T15:25:59Z',
      'requestedStartDate': '2022-05-11T15:25:59Z',
      'lastUpdated': '2022-05-11T15:26:04.320418257Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestSource': 'email',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Wireless',
      'incomingMailbox': 'HSCOttawa@bell.ca',
      'status': 'acknowledged',
      'originator': {'email': 'cbiorders@cbitelecom.com', 'name': 'Orders'},
      'preferredLanguage': 'en',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_WIRELESS'],
     'workOrder.status': ['new'],
     'source.orderDate': ['2022-05-11T15:25:59Z'],
     'source.focTarget': [0],
     'source.requestSource': ['email'],
     'workOrder.controlDesk': ['hscOttawa'],
     'lastUpdated': ['2022-05-11 15:26:04.32100+0000'],
     'source.status': ['acknowledged'],
     'source.requestedStartDate': ['2022-05-11T15:25:59Z'],
     'source.preferredLanguage': ['en'],
     'source.businessUnit': ['Wireless'],
     'workOrder.tags': ['CREATED_FROM_EMAIL_REQUEST',
      'AIML_PROCESSED',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
     'request_id': ['bsd_REQ-544752']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'HL-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544749',
     'lastUpdated': '2022-05-11T15:25:44.730818625Z',
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544749',
      'status': 'redistribute',
      'controlDesk': 'businessCare',
      'tags': ['CREATED_FROM_SMARTPATH',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544749',
      'externalId': 'REQ-544749',
      'orderDate': '2022-05-11T15:25:38Z',
      'requestedStartDate': '2022-05-11T15:25:38Z',
      'lastUpdated': '2022-05-11T15:25:44.729003168Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'serviceAssurance',
      'requestSource': 'smartpath',
      'billingAccount': '',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Retail',
      'crdDdst': 'ALQNB64',
      'status': 'inProgress',
      'product': 'sipTrunk',
      'serviceRegion': 'QC',
      'goldenCustomer': {'id': '1004698409', 'name': 'Polycor Inc.'},
      'customer': {'name': 'Polycor Inc.'},
      'creator': {'id': 'mylene.hebert',
       'email': 'mylene.hebert@bell.ca',
       'name': 'Mylene Hebert'},
      'originator': {'email': 'andre.breton@polycor.com',
       'phoneNumber': '819.652.2000 x4257 ',
       'name': 'Andre Breton '},
      'customerMarketSegment': 'Quebec SMB',
      'preferredLanguage': 'fr',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customer': [{'name': 'Polycor Inc.'}],
     'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'workOrder.status': ['redistribute'],
     'source.orderDate': ['2022-05-11T15:25:38Z'],
     'source.requestType': ['serviceAssurance'],
     'source.goldenCustomer': [{'name': 'Polycor Inc.', 'id': '1004698409'}],
     'source.focTarget': [0],
     'source.requestSource': ['smartpath'],
     'workOrder.controlDesk': ['businessCare'],
     'source.customerMarketSegment': ['Quebec SMB'],
     'lastUpdated': ['2022-05-11 15:25:44.73000+0000'],
     'source.status': ['inProgress'],
     'source.serviceRegion': ['QC'],
     'source.requestedStartDate': ['2022-05-11T15:25:38Z'],
     'source.preferredLanguage': ['fr'],
     'source.businessUnit': ['Retail'],
     'workOrder.tags': ['CREATED_FROM_SMARTPATH',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
     'request_id': ['bsd_REQ-544749'],
     'source.product': ['sipTrunk']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'Jr-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544739',
     'lastUpdated': '2022-05-11T15:23:45.725824118Z',
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544739',
      'status': 'redistribute',
      'controlDesk': 'businessCare',
      'group': 'sscAtelkaVoiceON',
      'tags': ['CREATED_FROM_PSS',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER',
       'AIML_PROCESSED']},
     'source': {'id': 'bsd_REQ-544739',
      'externalId': 'REQ-544739',
      'emailSubject': 'SSC/CLS – SS1059671441 - Business Lines / Lignes d’affaires - General - General inquiry / Renseignements généraux - Demande de renseignements -\xa0English -\xa0V:No/Non',
      'orderDate': '2022-05-11T15:23:34Z',
      'requestedStartDate': '2022-05-11T15:23:34Z',
      'lastUpdated': '2022-05-11T15:23:45.723983216Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'generalInquiry-othergeneral',
      'requestSource': 'pss',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Retail',
      'incomingMailbox': 'businesscare@bell.ca',
      'crdDdst': 'CRERZET',
      'status': 'inProgress',
      'product': 'businessLines',
      'serviceRegion': 'ON',
      'goldenCustomer': {'id': '1004926524', 'name': 'Frontier Networks Inc.'},
      'customer': {'name': 'Frontier Networks Inc.'},
      'originator': {'email': 'csturgeon@fmginc.com',
       'phoneNumber': '416 252 2424 x6816',
       'name': 'Chris Sturgeon'},
      'customerMarketSegment': 'Carrier Services OR',
      'preferredLanguage': 'en',
      'focTarget': 0},
     'OrderRelatedParty': {'value': 'no-data'},
     'SearchDetails': {'value': 'no-data'},
     'SearchFilter': {'value': 'no-data'},
     'AttributeFilter': {'value': 'no-data'},
     'AlwaysRejectFilter': {'value': 'no-data'},
     'FilterOperator': {'value': 'no-data'},
     'FilterGroup': {'value': 'no-data'},
     'FilterGroupOperator': {'value': 'no-data'},
     'FilterGroupModifier': {'value': 'no-data'}},
    'fields': {'source.customer': [{'name': 'Frontier Networks Inc.'}],
     'source.customerSupportModel': ['Standard'],
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'workOrder.status': ['redistribute'],
     'source.orderDate': ['2022-05-11T15:23:34Z'],
     'source.requestType': ['generalInquiry-othergeneral'],
     'source.goldenCustomer': [{'name': 'Frontier Networks Inc.',
       'id': '1004926524'}],
     'source.focTarget': [0],
     'source.requestSource': ['pss'],
     'workOrder.controlDesk': ['businessCare'],
     'source.customerMarketSegment': ['Carrier Services OR'],
     'lastUpdated': ['2022-05-11 15:23:45.72500+0000'],
     'source.status': ['inProgress'],
     'source.serviceRegion': ['ON'],
     'source.requestedStartDate': ['2022-05-11T15:23:34Z'],
     'source.preferredLanguage': ['en'],
     'source.businessUnit': ['Retail'],
     'workOrder.tags': ['CREATED_FROM_PSS',
      'SMARTPATH_DISTRIBUTION_MODE_FILTER',
      'AIML_PROCESSED'],
     'request_id': ['bsd_REQ-544739'],
     'source.product': ['businessLines']}},
   {'_index': 'bbm_aiml_stm_test_prod_3',
    '_type': '_doc',
    '_id': 'KL-9s4ABhhVSglz-m5ck',
    '_score': 2.01131,
    '_source': {'request_id': 'bsd_REQ-544737',
     'lastUpdated': '2022-05-11T15:23:54.747630792Z',
     'accessPolicyTag': ['DIVISION_RETAIL'],
     'OrderResponse': {'value': 'no-data'},
     'workOrder': {'id': 'bsd_REQ-544737',
      'status': 'completed',
      'followUpDate': '2022-05-12T03:00:00Z',
      'controlDesk': 'atlanticBtcSipt',
      'assignee': {'id': 'ad62384', 'name': 'Adam Graves'},
      'tags': ['CREATED_FROM_SMARTPATH',
       'SMARTPATH_DISTRIBUTION_MODE_FILTER']},
     'source': {'id': 'bsd_REQ-544737',
      'externalId': 'REQ-544737',
      'orderDate': '2022-05-11T15:23:16Z',
      'requestedStartDate': '2022-05-11T15:23:16Z',
      'startDate': '2022-05-11T15:23:21.181305283Z',
      'completedDate': '2022-05-11T15:23:52.129280217Z',
      'lastUpdated': '2022-05-11T15:23:54.746120812Z',
      'referredType': 'ServiceOrder',
      'sourceSystemId': 'BSD',
      'requestType': 'billingInquiry-otherbilling',
      'requestSource': 'smartpath',
      'billingAccount': '',
      'customerSupportModel': 'Standard',
      'businessUnit': 'Retail',
      'crdDdst': 'AASSGU2',
      'status': 'completed',
      'product': 'businessLines',
      'serviceRegion': 'NL',
      'goldenCustomer': {'id': '1005110594',
       'name': 'Newfoundland and Labrador Legal Aid Commission'},
      'customer': {'name': 'Newfoundland and Labrador Legal Aid Commission'},
      'creator': {'id': 'ad62384',

In [83]:
len(r['hits']['hits'])

260

In [84]:
r['hits']['hits'][0]['fields']

{'source.customer': [{'name': 'Eurofins Enviroment Testing Canada'}],
 'source.customerSupportModel': ['Standard'],
 'accessPolicyTag': ['DIVISION_RETAIL'],
 'workOrder.status': ['inProgress'],
 'source.orderDate': ['2022-05-11T15:26:28Z'],
 'source.requestType': ['change'],
 'source.goldenCustomer': [{'name': 'Eurofins Enviroment Testing Canada',
   'id': '1004996774'}],
 'source.focTarget': [0],
 'source.requestSource': ['smartpath'],
 'workOrder.controlDesk': ['bbscL1'],
 'source.customerMarketSegment': ['Ontario SMB - Mass'],
 'lastUpdated': ['2022-05-11 15:26:36.53800+0000'],
 'source.status': ['inProgress'],
 'source.serviceRegion': ['ON'],
 'source.requestedStartDate': ['2022-05-11T15:26:28Z'],
 'source.preferredLanguage': ['en'],
 'source.businessUnit': ['Retail'],
 'workOrder.tags': ['CREATED_FROM_SMARTPATH',
  'SMARTPATH_DISTRIBUTION_MODE_FILTER'],
 'request_id': ['bsd_REQ-544756'],
 'workOrder.assignee': [{'name': 'Marc Larivee', 'id': 'ba0cdrq'}],
 'source.product': ['businessInternet']}

In [37]:
def clean_resp_dict(resp):
    """Transform the response dict which can have nested fields into a flattened
    dict.
    Note: This works for current fields as of 04/22, and might need to be updated
    if more data fields are ingested."""
    
    cleaned_r_list = []

    for hit in resp['hits']['hits']:
        single_cleaned_r = {}
        for k, v in hit['fields'].items():
            if k == 'source.goldenCustomer' and 'id' in v[0].keys():
                single_cleaned_r[k] = v[0]['id']
            else:
                if len(v) == 1:
                    single_cleaned_r[k] = v[0]
                if len(v) > 1:
                    single_cleaned_r[k] = [' '.join(v)]
        cleaned_r_list.append(single_cleaned_r)

    return cleaned_r_list

In [38]:
cleaned_r_list =  clean_resp_dict(r)

In [39]:
df = pd.DataFrame(cleaned_r_list, columns=query_fields)

In [40]:
df.columns = [c.replace('.', '_') for c in query_fields]

In [41]:
df['source_requestedStartDate'] = pd.to_datetime(df.source_requestedStartDate)

In [44]:
df[(df.source_status != 'cancelled') & (df.source_status != 'completed')]

,request_id,accessPolicyTag,workOrder_status,workOrder_followUpDate,workOrder_controlDesk,workOrder_group,workOrder_assignee,workOrder_tags,source_orderDate,source_requestedStartDate,...,source_customerSupportModel,source_businessUnit,source_status,source_product,source_serviceRegion,source_goldenCustomer,source_customer,source_customerMarketSegment,source_preferredLanguage,source_focTarget
0,bsd_REQQA-468368,DIVISION_RETAIL,new,NaN,businessCare,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST SMARTPATH_DISTRIBU...,2022-04-07T18:09:44Z,2022-04-07 18:09:44+00:00,...,Standard,Retail,inProgress,NaN,EAST,NaN,NaN,Bell Atlantic,en,0
1,bsd_REQQA-468367,[EMAIL_WOA DIVISION_RETAIL],new,NaN,businessCare,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST SMARTPATH_DISTRIBU...,2022-04-07T18:09:42Z,2022-04-07 18:09:42+00:00,...,Standard,Retail,inProgress,NaN,EAST,NaN,NaN,Bell Atlantic,en,0
2,bsd_REQQA-468366,DIVISION_WIRELESS,new,NaN,hscToronto,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-07T18:08:39Z,2022-04-07 18:08:39+00:00,...,Standard,Wireless,acknowledged,NaN,NaN,NaN,NaN,NaN,en,0
3,bsd_REQQA-468365,DIVISION_WIRELESS,new,NaN,hscToronto,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-07T18:08:36Z,2022-04-07 18:08:36+00:00,...,Standard,Wireless,acknowledged,NaN,NaN,NaN,NaN,NaN,en,0
4,bsd_REQQA-468364,DIVISION_WIRELESS,new,NaN,hscToronto,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-07T18:08:32Z,2022-04-07 18:08:32+00:00,...,Standard,Wireless,acknowledged,NaN,NaN,NaN,NaN,NaN,en,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,bsd_REQQA-465564,DIVISION_WIRELESS,new,NaN,hscOttawa,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-06T15:23:17Z,2022-04-06 15:23:17+00:00,...,Standard,Wireless,acknowledged,NaN,NaN,NaN,NaN,NaN,en,0
3996,bsd_REQQA-465563,DIVISION_BMR,new,NaN,NaN,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST SMARTPATH_DISTRIBU...,2022-04-06T15:23:14Z,2022-04-06 15:23:14+00:00,...,Standard,BMR,acknowledged,NaN,NaN,NaN,NaN,Public Safety,en,0
3997,bsd_REQQA-465562,DIVISION_RETAIL,new,NaN,managedServicesSPOA,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-06T15:23:12Z,2022-04-06 15:23:12+00:00,...,Standard,Retail,acknowledged,managedServices,INTL,NaN,NaN,NaN,fr,0
3998,bsd_REQQA-465561,DIVISION_RETAIL,new,NaN,managedServicesSPOA,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-06T15:22:43Z,2022-04-06 15:22:43+00:00,...,Standard,Retail,acknowledged,businessLines,QC,NaN,NaN,NaN,fr,0
3999,bsd_REQQA-465560,DIVISION_RETAIL,new,NaN,businessCare,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-06T15:22:41Z,2022-04-06 15:22:41+00:00,...,Standard,Retail,acknowledged,sipTrunk,ON,NaN,NaN,NaN,en,10

In [42]:
df.source_status.value_counts()

acknowledged    3004
inProgress       988
completed          5
pending            2
cancelled          1
Name: source_status, dtype: int64

In [88]:
df.workOrder_assignee.value_counts()

{'name': 'Julian Fernandes', 'id': 'ju6105298'}         14
{'name': 'Agnes Agent', 'id': 'agnes.agent'}             1
{'name': 'Donald Advanced', 'id': 'donald.advanced'}     1
{'name': 'Grant M Robinson', 'id': 'grant.robinson'}     1
Name: workOrder_assignee, dtype: int64

In [79]:
df.columns

Index(['request_id', 'accessPolicyTag', 'workOrder_status',
       'workOrder_followUpDate', 'workOrder_controlDesk', 'workOrder_group ',
       'workOrder_assignee', 'workOrder_tags', 'source_orderDate',
       'source_requestedStartDate', 'source_requestType',
       'source_requestSource', 'source_customerSupportModel',
       'source_businessUnit', 'source_status', 'source_product',
       'source_serviceRegion', 'source_goldenCustomer', 'source_customer',
       'source_customerMarketSegment', 'source_preferredLanguage',
       'source_focTarget'],
      dtype='object')

In [72]:
df.head()

,request_id,accessPolicyTag,workOrder_status,workOrder_followUpDate,workOrder_controlDesk,workOrder_group,workOrder_assignee,workOrder_tags,source_orderDate,source_requestedStartDate,...,source_customerSupportModel,source_businessUnit,source_status,source_product,source_serviceRegion,source_goldenCustomer,source_customer,source_customerMarketSegment,source_preferredLanguage,source_focTarget
0,bsd_REQQA-463570,DIVISION_WIRELESS,new,NaN,hscToronto,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-05T18:17:49Z,2022-04-05 18:17:49+00:00,...,Standard,Wireless,acknowledged,NaN,NaN,1004888274,{'name': 'Bank of Montreal'},Quebec Enterprise,en,0
1,bsd_REQQA-463569,DIVISION_BMR,new,NaN,NaN,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST SMARTPATH_DISTRIBU...,2022-04-05T18:17:19Z,2022-04-05 18:17:19+00:00,...,Standard,BMR,acknowledged,NaN,NaN,NaN,NaN,Public Safety,en,0
2,bsd_REQQA-463568,DIVISION_WHOLESALE,new,NaN,localMigration,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-05T18:17:17Z,2022-04-05 18:17:17+00:00,...,Standard,Wholesale,acknowledged,businessLines,ON,NaN,NaN,NaN,en,0
3,bsd_REQQA-463567,DIVISION_RETAIL,new,NaN,managedServicesSPOA,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-05T18:17:15Z,2022-04-05 18:17:15+00:00,...,Standard,Retail,acknowledged,managedServices,INTL,NaN,NaN,NaN,fr,0
4,bsd_REQQA-463566,DIVISION_WHOLESALE,new,NaN,wholesaleBroadband,NaN,NaN,[CREATED_FROM_EMAIL_REQUEST AIML_PROCESSED SMA...,2022-04-05T18:17:12Z,2022-04-05 18:17:12+00:00,...,Standard,Wholesale,acknowledged,ethernet,ON,{},{},NaN,en,0

In [60]:
df[df.workOrder_tags.str.contains("SMARTPATH_DISTRIBUTION_MODE_FILTER")]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [47]:
with open("tmp/test_file.txt") as file:
    d = {}
    for i , line in enumerate(file):
        print(line)
        print(type(line))
        if i == 3:
            break

{"agent_id":"jeffrey.sanderson","full_name":"Jeffrey Sanderson","permissions":["OC-SmartPath-NetNewCreator","OC-SmartPath-Wholesale","OC-SmartPath-Retail","OC-SmartPath-BBM"]}

<class 'str'>
{"agent_id":"ka61257","full_name":"Kathleen Lambert","permissions":["OC-SmartPath-Wholesale","OC-SmartPath-Retail","OC-SmartPath-BBM"]}

<class 'str'>
{"agent_id":"bccs.0122911","full_name":"Samantha Clarke","permissions":["OC-SmartPath-NetNewCreator","OC-SmartPath-Wholesale","OC-SmartPath-Retail","OC-SmartPath-BBM"]}

<class 'str'>
{"agent_id":"kim.chiodo","full_name":"Kim Chiodo","permissions":["OC-SmartPath-NetNewCreator","OC-SmartPath-Wholesale","OC-SmartPath-Retail","OC-SmartPath-BBM"]}

<class 'str'>

In [48]:
a = '{"agent_id":"jeffrey.sanderson","full_name":"Jeffrey Sanderson","permissions":["OC-SmartPath-NetNewCreator","OC-SmartPath-Wholesale","OC-SmartPath-Retail","OC-SmartPath-BBM"]}'
json.loads(a)

{'agent_id': 'jeffrey.sanderson',
 'full_name': 'Jeffrey Sanderson',
 'permissions': ['OC-SmartPath-NetNewCreator',
  'OC-SmartPath-Wholesale',
  'OC-SmartPath-Retail',
  'OC-SmartPath-BBM']}

In [54]:
with open("tmp/test_file.txt") as file:

    for i, line in enumerate(file):
        print(i)
        if i == 5:
            break
        d = json.loads(line)
        print(d['agent_id'])
        print(d['permissions'])
        print(d['full_name'])

0
jeffrey.sanderson
['OC-SmartPath-NetNewCreator', 'OC-SmartPath-Wholesale', 'OC-SmartPath-Retail', 'OC-SmartPath-BBM']
Jeffrey Sanderson
1
ka61257
['OC-SmartPath-Wholesale', 'OC-SmartPath-Retail', 'OC-SmartPath-BBM']
Kathleen Lambert
2
bccs.0122911
['OC-SmartPath-NetNewCreator', 'OC-SmartPath-Wholesale', 'OC-SmartPath-Retail', 'OC-SmartPath-BBM']
Samantha Clarke
3
kim.chiodo
['OC-SmartPath-NetNewCreator', 'OC-SmartPath-Wholesale', 'OC-SmartPath-Retail', 'OC-SmartPath-BBM']
Kim Chiodo
4
susan.grimsdale
['OC-SmartPath-GoC-Level1', 'OC-SmartPath-GoC-Level2', 'OC-SmartPath-NetNewCreator', 'OC-SmartPath-Wholesale', 'OC-SmartPath-Retail', 'OC-SmartPath-BBM']
Susan Grimsdale-Holder
5

In [53]:
d

{'jeffrey.sanderson': {'full_name': 'Jeffrey Sanderson',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ka61257': {'full_name': 'Kathleen Lambert',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.0122911': {'full_name': 'Samantha Clarke',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'kim.chiodo': {'full_name': 'Kim Chiodo',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'susan.grimsdale': {'full_name': 'Susan Grimsdale-Holder',
  'permissions': ['OC-SmartPath-GoC-Level1',
   'OC-SmartPath-GoC-Level2',
   'OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'py6101652': {'full_name': 'Pyrave Thayananthan',
  'permissions': ['OC-SmartPath-Wireless', 'OC-SmartPath-NetNewCreator']},
 'margaret.brown': {'full_name': 'Margaret Brown',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.A552820': {'full_name': 'Paulette Fagan',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'lucie.des_ormeaux': {'full_name': 'Lucie Des Ormeaux',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'lo38119': {'full_name': 'Lorraine Gautreau',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ki65834': {'full_name': 'Kim Bowlin',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'jelliot1': {'full_name': 'Jessica Elliott',
  'permissions': ['OC-SmartPath-Wireless', 'OC-SmartPath-NetNewCreator']},
 'is37346': {'full_name': 'Isabelle Holmes',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'france.turcot': {'full_name': 'France Turcot',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'luc.clement': {'full_name': 'Luc Clement',
  'permissions': ['OC-SmartPath-Wireless', 'OC-SmartPath-NetNewCreator']},
 'em65803': {'full_name': "Emily O'Neill",
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n425141': {'full_name': 'Mervin Lieuw-Choy',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.6049145': {'full_name': 'Aime Bitwa',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'jane_r.richards': {'full_name': 'Jane Richards',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a531372': {'full_name': 'Regine Belizaire',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n373848': {'full_name': 'Paulette Luke',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ca66709': {'full_name': 'Catherine MacIsaac',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'linda_d.mccready': {'full_name': 'Linda McCready',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.p016432': {'full_name': 'Kim Godwin-Renaud',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.6049558': {'full_name': 'Brahim Lhacmuni',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ba0cfss': {'full_name': 'Natasha Page',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a338670': {'full_name': 'Charles Boulanger',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'wendy.knowles': {'full_name': 'Wendy Knowles',
  'permissions': ['OC-SmartPath-GoC-Level1',
   'OC-SmartPath-GoC-Level2',
   'OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'normand.pichette': {'full_name': 'Normand Pichette',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n435942': {'full_name': 'Kehinde Awonuga',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'noreen.jones': {'full_name': 'Noreen Jones',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'sandra.howe': {'full_name': 'Sandra Howe',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n414439': {'full_name': 'Chris Asimakopoulos',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'alain.duhamel': {'full_name': 'Alain Duhamel',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.A539230': {'full_name': 'Jean Brisebois',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'jason.ough': {'full_name': 'Jason Ough',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a235166': {'full_name': 'Christiane Reid',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'erin.malette': {'full_name': 'Christiane Reid', 'permissions': []},
 'bccs.n250686': {'full_name': 'Doris Tesolin',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'mylene.hebert': {'full_name': 'Mylene Hebert',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'david.filion': {'full_name': 'David Filion',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a594535': {'full_name': 'Gabriel Alvarez',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'genevieve.fournier': {'full_name': 'Genevieve Fournier',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'sh62832': {'full_name': 'Shirlee Davidson',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'de62800': {'full_name': 'Denise MacMillan-Meshcheryakov',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'isabelle.warren1': {'full_name': 'Isabelle Warren',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a304901': {'full_name': 'Sheila Adams',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'carole.lacelle': {'full_name': 'Carole Lacelle',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'prabhakar.iyer': {'full_name': 'Prabhakar Iyer',
  'permissions': ['OC-SmartPath-GoC-Level1',
   'OC-SmartPath-GoC-Level2',
   'OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'su62899': {'full_name': 'Susan Barry',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a489597': {'full_name': 'Lucie Bourret',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.p001862': {'full_name': 'Michael Fata',
  'permissions': ['OC-SmartPath-GoC-Level2',
   'OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bo66942': {'full_name': 'Bonnie Gorman',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n439653': {'full_name': 'Laraine Baker',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n435345': {'full_name': 'Kamile Ewan',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'be62403': {'full_name': 'Bernadette Payne',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.ex13908': {'full_name': 'Denise Watchorn',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ba00440': {'full_name': 'Jean-Paul Cordeiro',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.p007523': {'full_name': 'Asif Patel',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'el66498': {'full_name': 'Ellen Manson',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bojanabr': {'full_name': 'Bojana Brkic',
  'permissions': ['OC-SmartPath-Wireless', 'OC-SmartPath-NetNewCreator']},
 'corinne.barnes': {'full_name': 'Corinne Barnes',
  'permissions': ['OC-SmartPath-GoC-Level1',
   'OC-SmartPath-GoC-Level2',
   'OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a305250': {'full_name': 'Monique Borduas',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n419425': {'full_name': 'John Donlan',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n295601': {'full_name': 'Colleen Wilson',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'to66026': {'full_name': 'Todd Michalik',
  'permissions': ['OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.p009004': {'full_name': 'Michel Comtois',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a555284': {'full_name': 'James Wong',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'jacob.poulin': {'full_name': 'James Wong', 'permissions': []},
 'bccs.p001392': {'full_name': 'Rosemarie Scuderi',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'nathalie.champagne': {'full_name': 'Nathalie Champagne',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.a489702': {'full_name': 'Nancy Girard',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'stephane.cliche': {'full_name': 'Stephane Cliche',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'bccs.n358696': {'full_name': 'Janice Pottinger',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'gabriella.spadafora': {'full_name': 'Gabriella Spadafora',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'ez21572': {'full_name': 'Tina Lalonde',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'na6018914': {'full_name': 'Nadira Assous', 'permissions': []},
 'benoit.racette': {'full_name': 'Benoit Racette',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']},
 'remy.phanor': {'full_name': 'Remy Phanor',
  'permissions': ['OC-SmartPath-NetNewCreator',
   'OC-SmartPath-Wholesale',
   'OC-SmartPath-Retail',
   'OC-SmartPath-BBM']}}

In [33]:
a = json.loads(l2.strip('[]\n'))

In [35]:
a.pop('id', None)

'Ema'